from admin.channels_settings.add_channel import add_channel_handler
from admin.channels_settings.common import channel_settings_handler
from admin.channels_settings.remove_channel import remove_channel_handler
from admin.channels_settings.show_channels import show_channel_handler